Repository Trend-Now/front-end, pull requests merged in 2025-09, with the labels that each got.

#97 [FEAT] 게시글 0건일 때 빈 상태 컴포넌트 추가
  package.json
  src/entities/board/lottie/search.json
  src/entities/board/ui/BoardList.tsx
  src/entities/board/ui/BoardListEmpty.tsx
  src/entities/board/ui/BoardListHeader.tsx
  src/entities/board/ui/BoardTable.tsx
  src/entities/board/ui/index.ts
  src/features/board/ui/BoardSection.tsx
  src/views/boards/ui/Board.tsx
  src/views/hotBoards/ui/HotBoard.tsx
  src/widgets/search/ui/FixedBoardsSection.tsx
Labels: feature

#106 [FIX] 날짜 표기를 작성일(createdAt) 기준으로 변경
  src/widgets/post/ui/Header.tsx
Labels: fix

#111 [FEAT] 404페이지 구현
  src/app/not-found.tsx
  src/widgets/not-found/icon/ArrowLeft.tsx
  src/widgets/not-found/icon/error1.png
  src/widgets/not-found/icon/error2.png
  src/widgets/not-found/icon/error3.png
  src/widgets/not-found/icon/error4.png
  src/widgets/not-found/index.ts
  src/widgets/not-found/ui/BackButton.tsx
  src/widgets/not-found/ui/NotFoundSection.tsx
  src/widgets/not-found/ui/index.ts
Labels: feature

#119 [BUG] 검색 결과에서 pagination 작동 오류 수정
  src/entities/search/ui/SearchTypeTabs.tsx
  src/widgets/search/ui/FixedBoardsSection.tsx
Labels: bug

#121 [FIX] Appbar 레이아웃 수정 및 사용자 정보 클릭시 마이페이지로 이동
  src/features/header/ui/User.tsx
  src/widgets/header/ui/AppBar.tsx
Labels: fix

#125 [FIX] 게시물 상세 페이지 디자인 수정
  src/entities/comments/ui/Comment.tsx
  src/entities/comments/ui/Comments.tsx
  src/widgets/post/ui/Header.tsx
Labels: fix

#142 [FEAT] 쿠키 기반 로그인 및 개발환경 테스트 로그인 구현
  next.config.ts
  src/app/oauth/redirect/page.tsx
  src/features/login/ui/LoginModal.tsx
  src/features/login/ui/TestLoginButton.tsx
  src/shared/api/axios/axios.ts
Labels: feature

#143 [CHORE] dev -> main merge
  next.config.ts
  src/app/oauth/redirect/page.tsx
  src/features/login/ui/LoginModal.tsx
  src/features/login/ui/TestLoginButton.tsx
  src/shared/api/axios/axios.ts
Labels: chore

#146 [FEAT] 게시물 상세 페이지 버그 이슈 및 SSR 적용
  package.json
  src/app/(main)/(boards)/board/[boardId]/post/[postId]/page.tsx
  src/app/(main)/(boards)/hotboard/[boardId]/post/[postId]/page.tsx
  src/features/write/ui/PostEdit.tsx
  src/shared/api/axios/axios.ts
  src/shared/types/post.ts
  src/views/post/ui/Post.tsx
  src/widgets/post/ui/Content.tsx
Labels: feature

#152 [CHORE] LoginGuard 컴포넌트 주석처리
  src/app/(main)/(boards)/board/[boardId]/write/page.tsx
  src/app/(main)/(boards)/hotboard/[boardId]/write/page.tsx
Labels: chore

#164 [FEAT] 마이페이지 스크랩 취소 기능 추가
  .gitignore
  src/features/mypage/icons/ScrapFilledIcon.tsx
  src/features/mypage/icons/ScrapOutlinedIcon.tsx
  src/features/mypage/icons/index.ts
  src/features/mypage/index.ts
  src/features/mypage/ui/ScrapCancelButton.tsx
  src/features/mypage/ui/index.ts
  src/features/post/ui/ScrapToggleButton.tsx
  src/features/post/ui/index.ts
  src/features/scrap/ui/ScrapToggleButton.tsx
  src/features/scrap/ui/index.ts
  src/widgets/mypage/ui/MyScrapRow.tsx
  src/widgets/post/ui/Header.tsx
Labels: feature

#167 [CHORE] dev to main merge
  .gitignore
  next.config.ts
  package.json
  src/app/(main)/(boards)/board/[boardId]/post/[postId]/edit/page.tsx
  src/app/(main)/(boards)/board/[boardId]/write/page.tsx
  src/app/(main)/(boards)/hotboard/[boardId]/post/[postId]/edit/page.tsx
  src/app/(main)/(boards)/hotboard/[boardId]/write/page.tsx
  src/features/header/ui/User.tsx
  src/features/header/ui/UserServerComponent.tsx
  src/features/header/ui/index.ts
  src/features/login/ui/TestLoginButton.tsx
  src/features/mypage/icons/ScrapFilledIcon.tsx
  src/features/mypage/icons/ScrapOutlinedIcon.tsx
  src/features/mypage/icons/index.ts
  src/features/mypage/index.ts
  src/features/mypage/ui/ScrapCancelButton.tsx
  src/features/mypage/ui/index.ts
  src/features/post/ui/ScrapToggleButton.tsx
  src/features/post/ui/index.ts
  src/features/scrap/ui/ScrapToggleButton.tsx
  src/features/scrap/ui/index.ts
  src/features/write/ui/PostEdit.tsx
  src/features/write/ui/PostWrite.tsx
  src/shared/api/axios/axios.ts
  src/widgets/header/ui/AppBar.tsx
  src/widgets/mypage/ui/MyScrapRow.tsx
  src/widgets/post/ui/Header.tsx
Labels: chore

#169 [FEAT] 검색 결과 - 고정게시판 empty state에 후속액션 추가
  src/entities/board/ui/BoardList.tsx
  src/entities/board/ui/BoardListEmpty.tsx
  src/entities/search/ui/HotBoardSearchList.tsx
  src/features/board/ui/BoardWriteButton.tsx
  src/shared/ui/emptystate/EmptyState.tsx
  src/shared/ui/icons/24/Pencil24.tsx
  src/shared/ui/icons/Pencil.tsx
  src/shared/ui/index.ts
  src/widgets/search/ui/FixedBoardsSection.tsx
  src/widgets/search/ui/HotPostsSection.tsx
Labels: feature

#172 [CHORE] dev to main merge
  src/entities/board/ui/BoardList.tsx
  src/entities/board/ui/BoardListEmpty.tsx
  src/entities/search/ui/HotBoardSearchList.tsx
  src/features/board/ui/BoardWriteButton.tsx
  src/features/hotboard/ui/AISummary.tsx
  src/shared/ui/emptystate/EmptyState.tsx
  src/shared/ui/icons/24/Pencil24.tsx
  src/shared/ui/icons/Pencil.tsx
  src/shared/ui/index.ts
  src/widgets/search/ui/FixedBoardsSection.tsx
  src/widgets/search/ui/HotPostsSection.tsx
Labels: chore
